import subprocess
import os
import glob
import shutil
import uuid

def text_to_wav(text, wav_path):
    """
    Synthesize speech from text using F5-TTS CLI and save to a WAV file.
    :param text: Text to synthesize
    :param wav_path: Output WAV file path
    """
    # Create a unique temp file for the text
    temp_id = str(uuid.uuid4())
    text_file = f"tts_input_{temp_id}.txt"
    try:
        with open(text_file, "w", encoding="utf-8") as f:
            f.write(text)
        # Call the F5-TTS CLI
        cmd = [
            "f5-tts_infer-cli",
            "--gen_file", text_file,
            "--output_dir", "."
        ]
        subprocess.run(cmd, check=True)
        # Find the generated wav file (newest .wav in current dir)
        wav_files = sorted(glob.glob("*.wav"), key=os.path.getmtime, reverse=True)
        if not wav_files:
            raise Exception("No WAV file generated by F5-TTS CLI.")
        shutil.move(wav_files[0], wav_path)
    finally:
        if os.path.exists(text_file):
            os.remove(text_file)

def list_tts_models():
    """
    List available F5-TTS models.
    """
    return subprocess.run(["f5-tts_infer-cli", "--list_models"], capture_output=True, text=True).stdout.strip().split("\n") 